version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'security'
    reviewers:
      - 'DerTimonius'
    open-pull-requests-limit: 10
